# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Browser.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def back (self):
            self.webView.back()
    def forword (self):
            self.webView.forward()
    def reload (self):
            self.webView.reload()
    def goAddress (self):
        self.webView.load(QtCore.QUrl(url))
    def home (self):
            self.webView.load(QtCore.QUrl("http://www.google.com.eg"))
            self.ln_addressbar.setText("http://www.google.com.eg")
    def search (self):
            url = self.ln_addressbar.text()
            self.webView.load(QtCore.QUrl(url))
            if self.ln_addressbar.text() == '' : 
                self.ln_addressbar.setPlaceholderText('Enter The site Link')
            else :
                self.ln_addressbar.setText(url)
            
                
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName(_fromUtf8("ABC Browser"))
        MainWindow.resize(688, 561)
        MainWindow.setStyleSheet(_fromUtf8("\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
":disabled{\n"
"   color: rgb(130,130, 130);\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QMainWindow{\n"
"   background-color: rgb(80, 80, 80);\n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"   border: 0px solid red;\n"
"}\n"
"\n"
"QMainWindow::separator:hover {\n"
"   background-color: rgb(255, 170, 0);\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QPushButton{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(90, 90, 90), stop:1 rgb(60, 60, 60));\n"
"    border: 1px solid black;\n"
"    color:rgb(220,220,220);\n"
"    padding: 1ex 2ex;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(150, 150, 150), stop:1 rgb(120, 120, 120));\n"
"    color:rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(120, 120, 120), stop:1 rgb(90, 90, 90));\n"
"}\n"
"\n"
"QDialogButtonBox > QPushButton, QDialog > QPushButton, QWizard > QWidget > QPushButton{\n"
"    min-width: 5em;\n"
"    min-height: 1.4em;\n"
"}\n"
"\n"
"QPushButton#m_pbFolderTpl, QPushButton#m_pbFilenameTpl, QPushButton#m_pbInfo, QPushButton#m_pbSoundPlay\n"
"{\n"
"   background-color:transparent;\n"
"   border: 0px solid red;\n"
"\n"
"}\n"
"\n"
"QPushButton[text=\"...\"]{\n"
"    min-width: 1em;\n"
"}\n"
"\n"
"QPushButton#m_pbAdvancedSetting{\n"
"   background-color:transparent;\n"
"   border:0px solid red;\n"
"   padding: 0ex 0ex;\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QDockWidget\n"
"{\n"
"   background-color: rgb(90, 90, 90);\n"
"   border-top: 1px solid orange;\n"
"   color:rgb(220, 220, 220);\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"   background-color: rgb(90, 90, 90);\n"
"   border: 0px solid black;\n"
"\n"
"   padding: 0.4em;\n"
"}\n"
"\n"
"QDockWidget  .QWidget{\n"
"   background-color: rgb(40, 40, 40);\n"
"   color: rgb(200,200,200);\n"
"   border: 0px solid red;\n"
"}\n"
"\n"
"QDockWidget QScrollArea{\n"
"    border: 0px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QHeaderView::section{\n"
"   color: rgb(220,220,220);\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"   background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(90, 90, 90), stop:1 rgb(60, 60, 60));\n"
"   padding: 1ex;\n"
"}\n"
"\n"
"QHeaderView::section:first{\n"
"   border-top: 0px solid black;\n"
"   border-right: 0px solid black;\n"
"   border-bottom: 1px solid black;\n"
"   border-left: 0px solid black;\n"
"}\n"
"\n"
"QHeaderView::section:middle{\n"
"   border-top: 0px solid black;\n"
"   border-right: 0px solid black;\n"
"   border-bottom: 1px solid black;\n"
"   border-left: 1px solid black;\n"
"}\n"
"\n"
"QHeaderView::section:last{\n"
"   border-top: 0px solid black;\n"
"   border-right: 0px solid black;\n"
"   border-bottom: 1px solid black;\n"
"   border-left: 1px solid black;\n"
"}\n"
"\n"
"QHeaderView::section:hover{\n"
"     background-color:  qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(150, 150, 150), stop:1 rgb(120, 120, 120));\n"
"}\n"
"\n"
"QHeaderView::section:pressed{\n"
"     background-color:  qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(150, 150, 150), stop:1 rgb(120, 120, 120));\n"
"}\n"
"\n"
" /* style the sort indicator */\n"
"QHeaderView::down-arrow {\n"
"    image: url(\"UI:arrow_down_V2.png\");\n"
"\n"
"    width: 10px;\n"
"    height: 10px;\n"
"\n"
"    padding-right: 1ex;\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    image: url(\"UI:arrow_up_V2.png\");\n"
"\n"
"    width: 10px;\n"
"    height: 10px;\n"
"\n"
"    padding-right: 1ex;\n"
"}\n"
"\n"
"QTreeView#UIGroup_TreeView QHeaderView::section:first{\n"
"    border-left: 1px solid black;\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QScrollBar{\n"
"    background-color:  rgb(55, 55, 55);\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::horizontal{\n"
"    border:0px solid rgb(90, 90, 90);\n"
"    border-left: 0px solid red;\n"
"    border-right: 0px solid red;\n"
"\n"
"    margin: 0px 16px 0px 16px;\n"
"}\n"
"\n"
"QScrollBar::vertical {\n"
"    border: 0px solid rgb(90, 90, 90);\n"
"    border-top: 0px solid red;\n"
"    border-bottom: 0px solid red;\n"
"\n"
"    margin: 16px 0px 16px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle{\n"
"    background-color: rgb(110, 110, 110);\n"
"    border: 1px solid rgb(65, 65, 65);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background-color: rgb(130, 130, 130);\n"
"}\n"
"\n"
"QScrollBar::handle:pressed {\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgb(60, 60, 60), stop:1 rgb(90, 90, 90));\n"
"    border: 1px solid rgb(90, 90, 90);\n"
"    border-left:0px;\n"
"\n"
"    width: 15px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgb(90, 90, 90), stop:1 rgb(60, 60, 60));\n"
"    border: 1px solid rgb(90, 90, 90);\n"
"    border-right:0px;\n"
"\n"
"    width: 15px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgb(100, 100, 100), stop:1 rgb(150, 150, 150));\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgb(150, 150, 150), stop:1 rgb(100, 100, 100));\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:pressed{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgb(130, 130, 130), stop:1 rgb(180, 180, 180));\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:pressed{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgb(180, 180, 180), stop:1 rgb(130, 130, 130));\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(60, 60, 60), stop:1 rgb(90, 90, 90));\n"
"    border: 1px solid rgb(90, 90, 90);\n"
"    border-top:0px;\n"
"\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(90, 90, 90), stop:1 rgb(60, 60, 60));\n"
"    border: 1px solid rgb(90, 90, 90);\n"
"    border-bottom:0px;\n"
"\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(100, 100, 100), stop:1 rgb(150, 150, 150));\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(150, 150, 150), stop:1 rgb(100, 100, 100));\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:pressed{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(130, 130, 130), stop:1 rgb(180, 180, 180));\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:pressed{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(130, 130, 130));\n"
"}\n"
"\n"
"QScrollBar::left-arrow:horizontal{\n"
"    background-image: url(\"UI:arrow_left_V2.png\");\n"
"    background-position: center;\n"
"}\n"
"\n"
"QScrollBar::right-arrow{\n"
"    background-image: url(\"UI:arrow_right_V2.png\");\n"
"    background-position: center;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical{\n"
"    background-image: url(\"UI:arrow_up_V2.png\");\n"
"    background-position: center;\n"
"}\n"
"\n"
"QScrollBar::down-arrow:vertical{\n"
"    background-image: url(\"UI:arrow_down_V2.png\");\n"
"    background-position: center;\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QSplitter{\n"
"    background-color: transparent;\n"
"    border: 0px solid red;\n"
"}\n"
"\n"
"QSplitter::handle{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 0px solid green;\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QScrollArea {\n"
"    background-color: transparent;\n"
"    border: 0px solid red;\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/* FOLDER TREE                                                                          */\n"
"/*----------------------------------------------------------------------------*/\n"
"QTreeView{\n"
"    background-color: rgb(100, 100, 100);\n"
"    alternate-background-color:  rgb(90, 90, 90);\n"
"    border: 0px solid black;\n"
"}\n"
"\n"
"QTreeView:active{\n"
"    selection-background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(80, 80, 80), stop:1 rgb(60, 60, 60));\n"
"}\n"
"\n"
"QTreeView:!active{\n"
"    selection-background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(80, 80, 80), stop:1 rgb(70, 70, 70));\n"
"}\n"
"\n"
"QTreeView::item{\n"
"    color: rgb(220,220,220);\n"
"    border: 0px solid green;\n"
"}\n"
"\n"
"QTreeView::item:alternate{\n"
"}\n"
"\n"
"QTreeView::item:selected:!active{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(70, 70, 70), stop:1 rgb(50, 50, 50));\n"
"}\n"
"\n"
"QTreeView::item:selected:active{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(80, 80, 80), stop:1 rgb(60, 60, 60));\n"
"}\n"
"\n"
"QTreeView::item:hover{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(80, 80, 80), stop:1 rgb(60, 60, 60));\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:!has-siblings, QTreeView::branch:closed:has-children:has-siblings{\n"
"    image: url(UI:treeview_arrow_right.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings, QTreeView::branch:open:has-children:has-siblings{\n"
"    image: url(UI:treeview_arrow_down.png);\n"
"}\n"
"\n"
"QTreeView::indicator{\n"
"    border: 0px solid red;\n"
"    width: 14px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked{\n"
"     image: url(UI:checkbox_unchecked.png);\n"
" }\n"
"\n"
"QTreeView::indicator:unchecked:disabled{\n"
"     image: url(UI:checkbox_unchecked_disabled.png);\n"
" }\n"
"\n"
"QTreeView::indicator:checked{\n"
"     image: url(UI:checkbox_checked.png);\n"
" }\n"
"\n"
"QTreeView::indicator:checked:disabled{\n"
"     image: url(UI:checkbox_checked_disabled.png);\n"
"}\n"
"\n"
"QTreeView#UIGroup_TreeView{\n"
"    background-color: rgb(40, 40, 40);\n"
"    alternate-background-color:  rgb(50, 50, 50);\n"
"    border: 0px solid black;\n"
"}\n"
"\n"
"\n"
"QTreeView#UIGroup_TreeView:active{\n"
"    selection-background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(110, 110, 110), stop:1 rgb(100, 100, 100));\n"
"}\n"
"\n"
"QTreeView#UIGroup_TreeView:!active{\n"
"    selection-background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(80,80, 80), stop:1 rgb(70, 70, 70));\n"
"}\n"
"\n"
"\n"
"QTreeView#UIGroup_TreeView::item:selected:!active{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(80,80, 80), stop:1 rgb(70, 70, 70));\n"
"}\n"
"\n"
"QTreeView#UIGroup_TreeView::item:selected:active{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(110, 110, 110), stop:1 rgb(100, 100, 100));\n"
"}\n"
"\n"
"QTreeView#UIGroup_TreeView::item:hover{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(110, 110, 110), stop:1 rgb(100, 100, 100));\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"MyThumbListView{\n"
"    background-color: black;\n"
"}\n"
"\n"
"QListView{\n"
"    background-color: rgb(65, 65, 65);\n"
"    border: 0px solid black;\n"
"}\n"
"\n"
"QListView::item{\n"
"    color: rgb(20,20,20);\n"
"}\n"
"\n"
"QListView::item:alternate{\n"
" }\n"
"\n"
"QListView::item:selected{\n"
"    color: rgb(220,220,220);\n"
"}\n"
"\n"
"QListView::item:selected:!active{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(60, 60, 60), stop:1 rgb(60, 60, 60));\n"
"}\n"
"\n"
"QListView::item:selected:active{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(90, 90, 90), stop:1 rgb(60, 60, 60));\n"
" }\n"
"\n"
"QListView::item:hover{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(90, 90, 90), stop:1 rgb(60, 60, 60));\n"
"}\n"
"\n"
"QListView#UIGroup_ListView{\n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 0px solid black;\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QTableView{\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QMenuBar{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(120, 120, 120), stop:1 rgb(100, 100, 100));\n"
"}\n"
"\n"
"QMenuBar::item{\n"
"    background-color: transparent;\n"
"    color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"QMenuBar::item:selected{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(130, 130, 130));\n"
"    color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QMenu{\n"
"    background-color: rgb(60, 60, 60);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 0px solid red;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QMenu::item{\n"
"    background-color: transparent;\n"
"    border: 1px solid transparent;\n"
"    padding: 2px 25px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(150, 150, 150), stop:1 rgb(100, 100, 100));\n"
"    border: 1px solid transparent;\n"
"    color:rgb(220, 220, 220);\n"
"}\n"
"\n"
"QMenu::separator{\n"
"   height: 1px;\n"
"   background-color: rgb(220, 220, 220);\n"
"   margin: 5px 25px 5px 20px;\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QDialog{\n"
"    background-color:  rgb(95, 95, 95);\n"
"    border: 0px solid black;\n"
"}\n"
"\n"
"QDialog QWidget#qt_scrollarea_viewport > QWidget {\n"
"    border: 0px solid black;\n"
"}\n"
"\n"
"QDialog WScrollArea{\n"
"   background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"     border: 0px solid black;\n"
"     margin-top:-1px;\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/* TOP TAB BAR */\n"
"/*----------------------------------------------------------------------------*/\n"
"QTabBar{\n"
"    background-color: transparent;\n"
"    border:0px solid red;\n"
"    border-right-color: rgb(30, 144, 255);\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QTabBar[shape=\"0\"]::tab{\n"
"    min-width:3em;\n"
"    padding: 1ex 3ex;\n"
"}\n"
"\n"
"MyTabBar[shape=\"0\"]::tab:selected{\n"
"    border-bottom-color: rgb(120, 120, 120);\n"
"}\n"
"\n"
"QTabBar[shape=\"0\"]::tab:selected{\n"
"    background-color: rgb(120, 120, 120);\n"
"    border-bottom-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"MyTabWidget::tab-bar {\n"
"    left: 1px;\n"
"}\n"
"\n"
"MyTabBar::tab:selected{\n"
"    color: white;\n"
"    background-color: rgb(120, 120, 120);\n"
"     border-top-left-radius: 4px;\n"
"     border-top-right-radius: 4px;\n"
"     border-top:3px solid rgb(30, 144, 255);\n"
"}\n"
"\n"
"MyTabBar[shape=\"0\"]::tab:selected{\n"
"    border-bottom-color: rgb(120, 120, 120);\n"
"}\n"
"\n"
"MyTabWidget::pane{\n"
"    padding: 1px 0px;\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/* FOLDER TREE AND CATEGORY TABS*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QTabBar[shape=\"2\"]::tab{\n"
"    min-height:3em;\n"
"    padding: 3ex 1ex;\n"
"}\n"
"\n"
"QTabBar[shape=\"2\"]::tab:selected{\n"
"    background-color: rgb(100, 100, 100);\n"
"    border-left:3px solid rgb(30, 144, 255);\n"
"}\n"
"\n"
"/*\n"
"QTabBar::tab:first:selected{\n"
"    margin-left: 0px;\n"
"    margin-right: -2px;\n"
"}\n"
"\n"
"QTabBar::tab:middle:selected{\n"
"    margin-left: 0px;\n"
"    margin-right: -2px;\n"
" }\n"
"\n"
"QTabBar::tab:last:selected{\n"
"    margin-left: 0px;\n"
"    margin-right: 0px;\n"
"}\n"
"*/\n"
"\n"
"QTabBar[shape=\"0\"]::tab:!selected{\n"
"    margin-top: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:last:!selected{\n"
"    border-left:0px solid red;\n"
"    border-right:0px solid black;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover{\n"
"     background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(90, 90, 90), stop:1 rgb(60, 60, 60));\n"
"}\n"
"\n"
"QTabBar[shape=\"1\"]::tab:selected{\n"
"    border-top-color: rgb(40, 40, 40);\n"
"    margin-left: 0px;\n"
"    margin-right: -2px;\n"
"}\n"
"\n"
"QTabBar[shape=\"1\"]::tab:!selected{\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QTabBar[shape=\"0\"]::tab:selected{\n"
"    border-top-color: rgb(30, 144, 255);\n"
"}\n"
"\n"
"QTabBar[shape=\"1\"]::tab:selected{\n"
"    border-bottom-color: rgb(30, 144, 255);\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QProgressBar{\n"
"    background-color:  qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(90, 90, 90), stop:1 rgb(60, 60, 60));\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(180, 180, 0, 100), stop:1 rgba(60, 60, 60, 60));\n"
"    border: 1px solid rgba(180, 180, 180, 200);\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QToolBar{\n"
"    border: 0px;\n"
"}\n"
"\n"
"QToolBar:horizontal{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(100, 100, 100), stop:1 rgb(80, 80, 80));\n"
"}\n"
"\n"
"QToolBar:vertical{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgb(90, 90, 90), stop:1 rgb(60, 60, 60));\n"
"}\n"
"\n"
"QToolBar:separator{\n"
"   background-color:qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(90, 90, 90));;\n"
"   border-right: 0px solid black;\n"
"   border-bottom: 0px solid black;\n"
"\n"
"   width:1px;\n"
"   height:1px;\n"
"   margin:5px;\n"
"}\n"
"\n"
"QToolBar#UIPanosView_ToolBar{\n"
"    border-top: 1px solid black;\n"
"    border-bottom: 0px solid red;\n"
"}\n"
"\n"
"QToolBar#UIGroupsView_ToolBar{\n"
"    border-top: 1px solid black;\n"
"    border-bottom: 0px solid red;\n"
"}\n"
"\n"
"QToolBar#UIGroup_ToolBar{\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"\n"
"QToolBar#UIPano_ToolBar{\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QSlider::groove:horizontal {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(140, 140, 140));\n"
"    border: 0px solid rgb(60, 60, 60);\n"
"    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(140, 140, 140));\n"
"    border: 1px solid rgb(60, 60, 60);\n"
"    width: 8px;\n"
"    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"    border-radius: 2px;\n"
" }\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(220, 220, 220), stop:1 rgb(180, 180, 180));\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QStatusBar{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(90, 90, 90), stop:1 rgb(60, 60, 60));\n"
"    color: rgb(220, 220, 220);\n"
"    border: 0px solid red;\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"DlgSettings QToolButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(60, 60, 60), stop:1 rgb(90, 90, 90));\n"
"    color:rgb(220,220,220);\n"
"}\n"
"\n"
"DlgSettings QTabWidget::pane {\n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"DlgSettings QTabBar[shape=\"0\"]::tab:selected {\n"
"    background-color: rgb(60, 60, 60);\n"
"    color: white;\n"
"    border-top:3px solid rgb(30, 144, 255);\n"
"}\n"
"\n"
"QToolButton {\n"
"   background-color: transparent;\n"
"    border: 0px solid red;\n"
"    color:rgb(220, 220, 220);\n"
"}\n"
"\n"
"QToolButton#m_tbClose{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolButton::hover{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(150, 150, 150), stop:1 rgb(120, 120, 120));\n"
"}\n"
"\n"
"QToolButton::checked{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(150, 150, 150));\n"
"}\n"
"\n"
"QToolButton::pressed{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(120, 120, 120), stop:1 rgb(90, 90, 90));\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"]{\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QToolButton::menu-button{\n"
"    border: 0px solid red;\n"
"}\n"
"\n"
"QToolButton::menu-button:hover{\n"
"   background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(150, 150, 150));\n"
"}\n"
"\n"
"QToolButton::menu-button:pressed{\n"
"\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QLabel, QCheckBox, QRadioButton{\n"
"    color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QSpinBox, QDoubleSpinBox {\n"
"   background-color:  qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(150, 150, 150));\n"
"   border: 1px solid black;\n"
"   padding:0px;\n"
"\n"
"   selection-background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(120, 120, 120), stop:1 rgb(90, 90, 90));\n"
"   selection-color: rgb(25, 25, 25);\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button, QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"     subcontrol-origin: border;\n"
"     width: 16px;\n"
"     border-width: 0px;\n"
" }\n"
"\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button {\n"
"     subcontrol-position: top right;\n"
"}\n"
"\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button {\n"
"     subcontrol-position: bottom right;\n"
"}\n"
"\n"
"QSpinBox::up-arrow, QDoubleSpinBox::up-arrow {\n"
"     border-image: url(UI:spinbox_up.png);\n"
"     height:7px;\n"
" }\n"
"\n"
"QSpinBox::down-arrow, QDoubleSpinBox::down-arrow {\n"
"     border-image: url(UI:spinbox_down.png);\n"
"     height:7px;\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QCheckBox::indicator:unchecked{\n"
"     image: url(UI:checkbox_unchecked.png);\n"
" }\n"
"\n"
"QCheckBox::indicator:unchecked:disabled{\n"
"     image: url(UI:checkbox_unchecked_disabled.png);\n"
" }\n"
"\n"
"QCheckBox::indicator:checked{\n"
"     image: url(UI:checkbox_checked.png);\n"
" }\n"
"\n"
"QCheckBox::indicator:checked:disabled{\n"
"     image: url(UI:checkbox_checked_disabled.png);\n"
" }\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QRadioButton::indicator:unchecked{\n"
"     image: url(UI:radiobutton_unchecked.png);\n"
" }\n"
"\n"
"QRadioButton::indicator:unchecked:disabled{\n"
"     image: url(UI:radiobutton_unchecked_disabled.png);\n"
" }\n"
"\n"
"QRadioButton::indicator:checked{\n"
"     image: url(UI:radiobutton_checked.png);\n"
" }\n"
"\n"
"QRadioButton::indicator:checked:disabled{\n"
"     image: url(UI:radiobutton_checked_disabled.png);\n"
" }\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QLineEdit{\n"
"   background-color:  qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(150, 150, 150));\n"
"   border: 0px solid black;\n"
"   padding:0px;\n"
"   color:black;\n"
"\n"
"   selection-background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(120, 120, 120), stop:1 rgb(90, 90, 90));\n"
"   selection-color: black;\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QComboBox{\n"
"     border: 0px solid black;\n"
"     padding: 0px 18px 0px 3px;\n"
" }\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable{\n"
"     background-color:  qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(150, 150, 150));\n"
" }\n"
"\n"
"QComboBox:editable{\n"
"     background-color:  qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(150, 150, 150));\n"
"\n"
"    selection-background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(120, 120, 120), stop:1 rgb(90, 90, 90));\n"
"    selection-color: rgb(25, 25, 25);\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on{\n"
"     background-color:  qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(150, 150, 150));\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"     border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"     image: url(UI:dropdown_arrow.png);\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"/* fix group box */\n"
"QGroupBox{\n"
"    color: rgb(200, 200, 200);\n"
"    background-color: rgb(90, 90, 90);\n"
"    border: 1px solid black;\n"
"\n"
"    margin-top: 1.1em; /* leave space at the top for the title */\n"
"    margin-bottom: 0.1em; /* leave space at the top for the title */\n"
"\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"    border: 0px solid red;\n"
"\n"
"    subcontrol-origin: margin;\n"
"    top: 0px;\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QTextEdit{\n"
"    background-color: rgb(90, 90, 90);\n"
"    color: rgb(220,220,220);\n"
"    border: 3px solid rgb(90, 90, 90);\n"
"\n"
"   selection-background-color:  rgb(60, 60, 60) ;\n"
"   selection-color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QToolTip{\n"
"      background-color:  qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(180, 180, 180), stop:1 rgb(150, 150, 150));\n"
"}\n"
"\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"/*----------------------------------------------------------------------------*/\n"
"QWizard{\n"
"}\n"
"\n"
"QWizard .QWidget{\n"
"      background-color: rgb(40,40,40);\n"
"      color:rgb(220,220,220);\n"
"}\n"
"\n"
"QWizard .QFrame{\n"
"      background-color: rgb(40,40,40);\n"
"      color:rgb(220,220,220);\n"
"}\n"
"\n"
"QWizard  > .QWidget > .QLabel{\n"
"      background-color: rgb(40,40,40);\n"
"      color:rgb(220,220,220);\n"
"}\n"
"\n"
"QWizard QListView{\n"
"      background-color: rgb(60,60,60);\n"
"      color:rgb(220,220,220);\n"
"}\n"
"\n"
"\n"
"QWizardPage .QFrame{\n"
"    background-color: transparent;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"SearchLineEdit{\n"
"    background-color:  transparent;\n"
"    border: 0px solid black;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"SearchLineEdit>QLineEdit{\n"
"    background-color: rgb(160, 160, 160);\n"
"}\n"
""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/ABC.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tb_back = QtGui.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_back.setIcon(icon)
        self.tb_back.setObjectName(_fromUtf8("tb_back"))
        ############Event###############################
        self.tb_back.clicked.connect(self.back)
        ################################################
        self.gridLayout.addWidget(self.tb_back, 0, 0, 1, 1)
        self.tb_reload = QtGui.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_reload.setIcon(icon1)
        self.tb_reload.setObjectName(_fromUtf8("tb_reload"))
        ############Event###############################
        self.tb_reload.clicked.connect(self.reload)
        ################################################
        self.gridLayout.addWidget(self.tb_reload, 0, 1, 1, 1)
        self.tb_forword = QtGui.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/forword.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_forword.setIcon(icon2)
        self.tb_forword.setObjectName(_fromUtf8("tb_forword"))
        ############Event###############################
        self.tb_forword.clicked.connect(self.forword)
        ################################################
        self.gridLayout.addWidget(self.tb_forword, 0, 2, 1, 1)
        self.tb_home = QtGui.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_home.setIcon(icon3)
        self.tb_home.setObjectName(_fromUtf8("tb_home"))
        ############Event###############################
        self.tb_home.clicked.connect(self.home)
        ################################################
        self.gridLayout.addWidget(self.tb_home, 0, 3, 1, 1)
        self.ln_addressbar = QtGui.QLineEdit(self.centralwidget)
        self.ln_addressbar.setObjectName(_fromUtf8("ln_addressbar"))
        #####################################################
        self.gridLayout.addWidget(self.ln_addressbar, 0, 4, 1, 1)
        self.tb_search = QtGui.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_search.setIcon(icon4)
        self.tb_search.setObjectName(_fromUtf8("tb_search"))
        ############Event###############################
        self.tb_search.clicked.connect(self.search)
        ################################################
        self.gridLayout.addWidget(self.tb_search, 0, 5, 1, 1)
        self.webView = QtWebKit.QWebView(self.centralwidget)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))    
        self.gridLayout.addWidget(self.webView, 1, 0, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ABC Browser", None))

        self.tb_back.setText(_translate("Back", "...", None))
        self.tb_reload.setText(_translate("Refresh", "...", None))
        self.tb_forword.setText(_translate("Forward", "...", None))
        self.tb_home.setText(_translate("Home", "...", None))
        self.tb_search.setText(_translate("Search", "...", None))

from PyQt4 import QtWebKit

